export const TITLE_FONT = '"Fredoka", "Baloo 2", "Nunito", sans-serif';
export const BODY_FONT = '"Nunito", "Quicksand", Arial, sans-serif';
export const STAR_FONT = '"Baloo 2", "Quicksand", "Nunito", sans-serif';

export function getTheme(darkMode) {
  return darkMode
    ? {
        pageBg: "linear-gradient(180deg, #0f172a 0%, #162033 35%, #1b263b 100%)",
        cardBg: "linear-gradient(180deg, rgba(37, 52, 74, 0.96) 0%, rgba(34, 50, 74, 0.98) 100%)",
        cardBgSoft: "#23324a",
        panelBg: "linear-gradient(180deg, #1d2a3f 0%, #22324a 100%)",
        border: "#3b4f6a",
        borderSoft: "#4a5d78",
        text: "#e5eefc",
        title: "#9bc4ff",
        muted: "#a9bdd8",
        inputBg: "#162033",
        inputBorder: "#41546f",
        inputText: "#f8fbff",
        buttonBg: "#22324a",
        buttonBorder: "#4b6584",
        buttonText: "#dbeafe",
        buttonPrimaryBg: "linear-gradient(180deg, #4f8fd8 0%, #3b73b9 100%)",
        buttonPrimaryBorder: "#72a7e5",
        buttonPrimaryText: "#ffffff",
        noteBg: "#162033",
        noteBorder: "#3b4f6a",
        noteText: "#d7e4f7",
        dangerBg: "linear-gradient(180deg, #3a2328 0%, #47292f 100%)",
        dangerBorder: "#8b5a63",
        dangerText: "#ffd7df",
        footerBorder: "#3b4f6a",
        starTint: "rgba(147, 197, 253, 0.16)",
        starActiveBg: "linear-gradient(180deg, #ffe58f 0%, #facc15 100%)",
        starActiveBorder: "#fbbf24",
        starActiveText: "#1f2937",
        urgentActiveBg: "linear-gradient(180deg, #ffb072 0%, #fb923c 100%)",
        urgentActiveBorder: "#f97316",
        urgentActiveText: "#1f2937",
      }
    : {
        pageBg: "linear-gradient(180deg, #eef6ff 0%, #f8fbff 35%, #f4f8fc 100%)",
        cardBg: "linear-gradient(180deg, rgba(255,255,255,0.98) 0%, rgba(247,251,255,0.98) 100%)",
        cardBgSoft: "#ffffff",
        panelBg: "linear-gradient(180deg, #ffffff 0%, #f7fbff 100%)",
        border: "#dbeafe",
        borderSoft: "#bfdbfe",
        text: "#1f2937",
        title: "#1e3a8a",
        muted: "#64748b",
        inputBg: "#ffffff",
        inputBorder: "#cbd5e1",
        inputText: "#0f172a",
        buttonBg: "#f8fbff",
        buttonBorder: "#bfdbfe",
        buttonText: "#1e3a8a",
        buttonPrimaryBg: "linear-gradient(180deg, #60a5fa 0%, #3b82f6 100%)",
        buttonPrimaryBorder: "#60a5fa",
        buttonPrimaryText: "#ffffff",
        noteBg: "#f8fbff",
        noteBorder: "#e0f2fe",
        noteText: "#475569",
        dangerBg: "linear-gradient(180deg, #fff4f5 0%, #ffe8eb 100%)",
        dangerBorder: "#f7b6c2",
        dangerText: "#8a1c35",
        footerBorder: "#dbeafe",
        starTint: "rgba(96, 165, 250, 0.18)",
        starActiveBg: "linear-gradient(180deg, #fde68a 0%, #facc15 100%)",
        starActiveBorder: "#f59e0b",
        starActiveText: "#1f2937",
        urgentActiveBg: "linear-gradient(180deg, #fdba74 0%, #fb923c 100%)",
        urgentActiveBorder: "#ea580c",
        urgentActiveText: "#1f2937",
      };
}

export function getStyles(theme, isMobile, darkMode) {
  return {
    page: {
      minHeight: "100vh",
      background: theme.pageBg,
      padding: isMobile ? "16px 12px 24px" : "24px",
      fontFamily: BODY_FONT,
      display: "flex",
      justifyContent: "center",
      color: theme.text,
      boxSizing: "border-box",
    },
    wrapper: { width: "100%", maxWidth: "1020px", position: "relative", minWidth: 0 },
    row: { display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap", minWidth: 0 },
    topBar: { display: "grid", gap: isMobile ? "10px" : "12px", marginBottom: isMobile ? "16px" : "18px" },
    headerMain: isMobile
      ? { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: "12px", flexWrap: "nowrap", minWidth: 0 }
      : { display: "grid", gridTemplateColumns: "auto 1fr auto", alignItems: "center", gap: "24px", minWidth: 0 },
    mascotWrap: { display: "flex", alignItems: isMobile ? "flex-end" : "center", justifyContent: "flex-start", flex: isMobile ? 1 : "0 0 auto", minWidth: 0 },
    headerRight: { display: "flex", flexDirection: "column", alignItems: isMobile ? "stretch" : "flex-end", justifyContent: "center", gap: isMobile ? "10px" : "12px", minWidth: isMobile ? "150px" : "170px", flexShrink: 0, position: "relative" },
    headerButtons: { display: "flex", flexDirection: "column", gap: "10px", width: "100%" },
    headerButton: { width: "100%", minHeight: "52px", display: "flex", alignItems: "center", justifyContent: "center", boxSizing: "border-box" },
    titleSticker: {
      width: isMobile ? "132px" : "150px",
      height: isMobile ? "132px" : "150px",
      objectFit: "contain",
      cursor: "pointer",
      userSelect: "none",
      display: "block",
      filter: darkMode
        ? "drop-shadow(0 8px 18px rgba(59, 130, 246, 0.22)) drop-shadow(0 0 16px rgba(147, 197, 253, 0.22))"
        : "drop-shadow(0 8px 18px rgba(96, 165, 250, 0.18)) drop-shadow(0 0 14px rgba(120, 160, 255, 0.22))",
      transformOrigin: "center bottom",
    },
    titleBlock: { display: "grid", justifyItems: "center", alignContent: "center", gap: isMobile ? "4px" : "6px", marginTop: isMobile ? "2px" : "0px", marginBottom: isMobile ? "2px" : "0px", textAlign: "center", minWidth: 0 },
    titleText: {
      margin: 0,
      fontSize: isMobile ? "34px" : "40px",
      color: theme.title,
      fontFamily: TITLE_FONT,
      fontWeight: 800,
      letterSpacing: "0.3px",
      lineHeight: 1.02,
      textAlign: "center",
      whiteSpace: "nowrap",
      minWidth: 0,
      textShadow: darkMode
        ? "0 0 12px rgba(147, 197, 253, 0.24), 0 0 2px rgba(255,255,255,0.12)"
        : "0 0 12px rgba(96, 165, 250, 0.14), 0 0 2px rgba(255,255,255,0.16)",
    },
    starSummaryWrap: { position: "relative", display: "flex", justifyContent: "center", width: "100%", minWidth: 0 },
    starSummaryButton: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: isMobile ? "8px" : "10px", minHeight: "44px", padding: isMobile ? "2px 8px" : "4px 10px", borderRadius: "999px", cursor: "pointer", userSelect: "none", color: theme.title, minWidth: 0 },
    starSummaryIcon: { fontSize: isMobile ? "20px" : "22px", lineHeight: 1, flexShrink: 0, filter: "drop-shadow(0 0 8px rgba(255, 215, 100, 0.35))" },
    starSummaryTextWrap: { display: "grid", gap: "0px", minWidth: 0 },
    starSummaryCount: { fontFamily: STAR_FONT, fontWeight: 700, fontSize: isMobile ? "18px" : "20px", lineHeight: 1.05, color: "#ffd966", whiteSpace: "nowrap", textShadow: "0 0 10px rgba(255, 215, 100, 0.35)" },
    starSummaryLabel: { fontFamily: STAR_FONT, fontWeight: 600, fontSize: isMobile ? "13px" : "14px", lineHeight: 1.05, color: theme.muted, whiteSpace: "nowrap" },
    card: { background: theme.cardBg, borderRadius: "18px", boxShadow: darkMode ? "0 10px 24px rgba(2, 6, 23, 0.32)" : "0 8px 22px rgba(148, 163, 184, 0.14)", border: `1px solid ${theme.border}`, padding: isMobile ? "14px" : "16px", marginBottom: "12px", position: "relative", overflow: "hidden", minWidth: 0, boxSizing: "border-box", backdropFilter: "blur(8px)" },
    cardStars: { position: "absolute", top: "10px", right: "14px", fontSize: "12px", color: theme.starTint, letterSpacing: "4px", pointerEvents: "none", userSelect: "none" },
    input: { width: "100%", maxWidth: "100%", padding: "10px 12px", borderRadius: "12px", border: `1px solid ${theme.inputBorder}`, fontSize: "14px", boxSizing: "border-box", fontFamily: BODY_FONT, background: theme.inputBg, color: theme.inputText, minWidth: 0, display: "block" },
    archiveDateInput: { width: "100%", maxWidth: "100%", padding: "10px 12px", minHeight: "44px", borderRadius: "12px", border: `1px solid ${theme.inputBorder}`, fontSize: isMobile ? "16px" : "14px", lineHeight: 1.2, boxSizing: "border-box", fontFamily: BODY_FONT, background: theme.inputBg, color: theme.inputText, minWidth: 0, display: "block", WebkitAppearance: "none", appearance: "none" },
    textarea: { width: "100%", maxWidth: "100%", padding: "10px 12px", borderRadius: "12px", border: `1px solid ${theme.inputBorder}`, fontSize: "14px", minHeight: "90px", resize: "vertical", boxSizing: "border-box", fontFamily: BODY_FONT, background: theme.inputBg, color: theme.inputText, minWidth: 0, display: "block" },
    button: { padding: "10px 14px", borderRadius: "12px", border: `1px solid ${theme.buttonBorder}`, background: theme.buttonBg, color: theme.buttonText, cursor: "pointer", fontSize: "14px", fontFamily: BODY_FONT, fontWeight: 700, boxSizing: "border-box", minHeight: "44px", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    buttonPrimary: { padding: "10px 14px", borderRadius: "12px", border: `1px solid ${theme.buttonPrimaryBorder}`, background: theme.buttonPrimaryBg, color: theme.buttonPrimaryText, cursor: "pointer", fontSize: "14px", fontFamily: BODY_FONT, fontWeight: 700, boxShadow: darkMode ? "0 6px 16px rgba(59, 130, 246, 0.18)" : "0 6px 16px rgba(59, 130, 246, 0.22)", boxSizing: "border-box", minHeight: "44px", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    smallButton: { padding: "8px 12px", minHeight: "44px", borderRadius: "10px", border: `1px solid ${theme.border}`, background: theme.cardBgSoft, color: theme.buttonText, cursor: "pointer", fontSize: "13px", fontFamily: BODY_FONT, fontWeight: 700, boxSizing: "border-box", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    taskName: { fontWeight: 800, margin: 0, color: theme.text },
    muted: { color: theme.muted, fontSize: "12px" },
    noteText: { color: theme.noteText, fontSize: "14px", whiteSpace: "pre-wrap", marginTop: "6px", background: theme.noteBg, border: `1px solid ${theme.noteBorder}`, borderRadius: "10px", padding: "10px", minWidth: 0, overflowWrap: "anywhere", boxSizing: "border-box" },
    stickerMenu: { position: "absolute", right: 0, top: "58px", width: isMobile ? "min(380px, calc(100vw - 24px))" : "min(380px, calc(100vw - 32px))", background: theme.panelBg, borderRadius: "16px", boxShadow: darkMode ? "0 16px 36px rgba(2, 6, 23, 0.35)" : "0 16px 36px rgba(148, 163, 184, 0.22)", padding: isMobile ? "12px" : "14px", zIndex: 10, border: `1px solid ${theme.border}`, boxSizing: "border-box", minWidth: 0, overflowX: "hidden" },
    stickerMessage: { marginTop: "8px", fontSize: "12px", color: theme.muted, lineHeight: 1.4, overflowWrap: "anywhere" },
    archiveTaskRow: { display: "grid", gap: "8px", minWidth: 0 },
    helperText: { fontSize: "12px", color: theme.muted, lineHeight: 1.45, overflowWrap: "anywhere" },
    galleryGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(74px, 1fr))", gap: "10px", marginTop: "10px" },
    galleryTile: { borderRadius: "14px", border: `1px solid ${theme.border}`, background: theme.cardBgSoft, padding: "8px", display: "grid", gap: "6px", justifyItems: "center", transition: "transform 0.18s ease, box-shadow 0.18s ease", minHeight: "84px" },
    galleryThumb: { width: "56px", height: "56px", objectFit: "contain", transition: "transform 0.18s ease", pointerEvents: "auto", userSelect: "none" },
    galleryExpandedOverlay: { position: "fixed", inset: 0, background: darkMode ? "rgba(2, 6, 23, 0.62)" : "rgba(15, 23, 42, 0.38)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 9998, padding: "24px" },
    galleryExpandedCard: { background: theme.cardBgSoft, borderRadius: "20px", border: `1px solid ${theme.border}`, boxShadow: darkMode ? "0 20px 50px rgba(2, 6, 23, 0.45)" : "0 20px 50px rgba(15, 23, 42, 0.2)", padding: "18px", maxWidth: "min(92vw, 560px)", maxHeight: "90vh", display: "grid", gap: "10px", justifyItems: "center" },
    galleryExpandedImage: { maxWidth: "min(80vw, 512px)", maxHeight: "70vh", objectFit: "contain" },
    footerText: { fontSize: "14px", lineHeight: 1.65, color: theme.muted, overflowWrap: "anywhere" },
    infoPanelScrollArea: { marginTop: "10px", maxHeight: isMobile ? "min(50vh, 420px)" : "none", overflowY: isMobile ? "auto" : "visible", WebkitOverflowScrolling: "touch", paddingRight: isMobile ? "4px" : 0 },
    infoPanel: { position: isMobile ? "fixed" : "absolute", left: isMobile ? "12px" : "auto", right: isMobile ? "12px" : 0, transform: "none", top: isMobile ? "72px" : "48px", width: isMobile ? "auto" : "min(380px, calc(100vw - 32px))", maxWidth: isMobile ? "400px" : "none", maxHeight: isMobile ? "calc(100vh - 96px)" : "none", margin: isMobile ? "0 auto" : 0, background: theme.panelBg, borderRadius: "16px", boxShadow: darkMode ? "0 16px 36px rgba(2, 6, 23, 0.35)" : "0 16px 36px rgba(148, 163, 184, 0.22)", padding: isMobile ? "12px" : "14px", zIndex: 10, border: `1px solid ${theme.border}`, boxSizing: "border-box", minWidth: 0, overflowX: "hidden", overflowY: "auto", WebkitOverflowScrolling: "touch" },
    starPanel: { position: "absolute", left: "50%", transform: "translateX(-50%)", top: "calc(100% + 8px)", width: isMobile ? "min(320px, calc(100vw - 24px))" : "min(300px, calc(100vw - 32px))", background: theme.panelBg, borderRadius: "16px", boxShadow: darkMode ? "0 16px 36px rgba(2, 6, 23, 0.35)" : "0 16px 36px rgba(148, 163, 184, 0.22)", padding: isMobile ? "12px" : "14px", zIndex: 10, border: `1px solid ${theme.border}`, boxSizing: "border-box", minWidth: 0, overflowX: "hidden" },
    panelActionRow: { display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3, minmax(0, 1fr))", gap: "8px", marginBottom: "12px", width: "100%", minWidth: 0 },
    panelActionButton: { padding: "10px 8px", borderRadius: "12px", border: `1px solid ${theme.buttonBorder}`, background: theme.buttonBg, color: theme.buttonText, cursor: "pointer", fontSize: "12px", fontFamily: BODY_FONT, fontWeight: 700, whiteSpace: "normal", textAlign: "center", lineHeight: 1.15, overflowWrap: "anywhere", boxSizing: "border-box", minHeight: "44px", display: "flex", alignItems: "center", justifyContent: "center", width: "100%", maxWidth: "100%", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    detailsToggle: { padding: "8px 10px", minHeight: "44px", borderRadius: "10px", border: `1px solid ${theme.border}`, background: theme.cardBgSoft, color: theme.buttonText, cursor: "pointer", fontSize: "13px", fontFamily: BODY_FONT, fontWeight: 700, boxSizing: "border-box", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation", display: "inline-flex", alignItems: "center", justifyContent: "center" },
    footerBar: { marginTop: "18px", padding: "10px 14px", borderTop: `1px solid ${theme.footerBorder}`, display: "grid", gap: "6px", justifyItems: "center", color: theme.muted, fontSize: "12px" },
    footerBarText: { color: theme.muted, fontSize: "12px", lineHeight: 1.5, textAlign: "center" },
    footerLinkRow: { display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "center", justifyContent: "center" },
    footerBarLink: { color: darkMode ? "#9ec9ff" : "#2563eb", textDecoration: "none", fontWeight: 700, fontSize: "12px" },
    footerDivider: { color: theme.muted, fontSize: "12px" },
    starActionRow: { display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3, minmax(0, 1fr))", gap: "8px", marginTop: "10px", width: "100%", minWidth: 0 },
    starActionButton: { padding: "10px 6px", borderRadius: "12px", border: `1px solid ${theme.buttonBorder}`, background: theme.buttonBg, color: theme.buttonText, cursor: "pointer", fontSize: "12px", fontFamily: BODY_FONT, fontWeight: 700, whiteSpace: "normal", textAlign: "center", lineHeight: 1.15, overflowWrap: "anywhere", boxSizing: "border-box", minHeight: "44px", display: "flex", alignItems: "center", justifyContent: "center", width: "100%", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    dangerSection: { marginTop: "12px", padding: "12px", borderRadius: "14px", border: `1px solid ${theme.dangerBorder}`, background: theme.dangerBg, display: "grid", gap: "8px", minWidth: 0, overflowX: "hidden" },
    dangerText: { fontSize: "12px", lineHeight: 1.5, color: theme.dangerText, overflowWrap: "anywhere" },
    dangerButton: { padding: "10px 14px", borderRadius: "12px", border: `1px solid ${theme.dangerBorder}`, background: darkMode ? "#512e35" : "#fff0f2", color: theme.dangerText, cursor: "pointer", fontSize: "13px", fontFamily: BODY_FONT, fontWeight: 800, width: "100%", boxSizing: "border-box", minHeight: "44px", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    archiveCompactCard: { background: theme.cardBgSoft, border: `1px solid ${theme.border}`, borderRadius: "14px", padding: "10px 12px", display: "grid", gap: "8px", boxShadow: darkMode ? "0 6px 14px rgba(2, 6, 23, 0.16)" : "0 3px 8px rgba(148, 163, 184, 0.08)", minWidth: 0, boxSizing: "border-box" },
    archiveCardHeader: { display: "flex", justifyContent: "space-between", gap: "10px", alignItems: "center", minWidth: 0 },
    archiveTitleRow: { display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap", minWidth: 0, flex: 1 },
    archiveTaskName: { color: theme.text, fontWeight: 800, fontSize: "14px", lineHeight: 1.3, overflowWrap: "anywhere" },
    archiveInlineNoteButton: { padding: "6px 10px", minHeight: "36px", borderRadius: "999px", border: `1px solid ${theme.border}`, background: "transparent", color: theme.muted, cursor: "pointer", fontSize: "11px", fontFamily: BODY_FONT, fontWeight: 600, lineHeight: 1.2, boxSizing: "border-box", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    archiveUndoButton: { padding: "8px 12px", minHeight: "44px", borderRadius: "10px", border: `1px solid ${theme.border}`, background: theme.cardBgSoft, color: theme.buttonText, cursor: "pointer", fontSize: "12px", fontFamily: BODY_FONT, fontWeight: 700, flexShrink: 0, boxSizing: "border-box", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation" },
    archiveFilterGrid: { display: "grid", gap: "10px", gridTemplateColumns: isMobile ? "1fr" : "minmax(0, 1fr) minmax(0, 1fr) auto", width: "100%", minWidth: 0, alignItems: isMobile ? "start" : "end" },
    archiveFilterCell: { minWidth: 0, width: "100%", boxSizing: "border-box", display: "grid", gap: "4px", alignContent: "start" },
    archiveFilterAction: { display: "flex", alignItems: "flex-end", minWidth: 0, width: "100%", boxSizing: "border-box", justifyContent: "stretch" },
    fullWidthButton: { width: "100%", maxWidth: "100%", boxSizing: "border-box" },
    controlsRow: { display: "flex", flexWrap: "wrap", gap: "8px", marginBottom: "14px", position: "relative", alignItems: "center", justifyContent: "center" },
    taskHeaderRow: { display: "grid", gridTemplateColumns: "1fr", gap: "10px", minWidth: 0 },
    taskTitleRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px", minWidth: 0 },
    taskActionRow: { display: "flex", flexWrap: "nowrap", gap: "8px", justifyContent: "flex-start", alignItems: "center", minWidth: 0, width: "100%" },
    taskActionButton: { flex: isMobile ? "1 1 0" : "0 0 auto", minWidth: isMobile ? 0 : "auto", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
    taskTitleText: { fontWeight: 800, margin: 0, color: theme.text, textAlign: "left", minWidth: 0, flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    taskMetaText: { color: theme.muted, fontSize: isMobile ? "11px" : "12px", whiteSpace: "nowrap", flexShrink: 0, marginLeft: "auto", textAlign: "right" },
    detailToggleButton: { width: "100%", padding: "10px 12px", minHeight: "44px", borderRadius: "12px", border: `1px solid ${theme.border}`, background: theme.cardBgSoft, color: theme.buttonText, cursor: "pointer", fontSize: "13px", fontFamily: BODY_FONT, fontWeight: 700, boxSizing: "border-box", transition: "transform 0.15s ease, box-shadow 0.15s ease, background 0.12s ease", touchAction: "manipulation", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px" },
    detailsPanel: { marginTop: "8px", overflow: "hidden" },
    checklistRow: { display: "flex", alignItems: "center", gap: "8px", minWidth: 0 },
    checklistTextInput: { flex: 1, minWidth: 0 },
    checklistItemText: { color: theme.noteText, fontSize: "14px", lineHeight: 1.5, overflowWrap: "anywhere", flex: 1 },
  };
}
